/**
 * The name a code block's language is shown under — `TypeScript`, not the
 * fence's `typescript` or `ts` (owner, 2026-10-06). Unknown names keep their
 * spelling with a capital first letter.
 */
const NAMES: Record<string, string> = {
  bash: 'Bash',
  c: 'C',
  'c++': 'C++',
  cpp: 'C++',
  cs: 'C#',
  csharp: 'C#',
  css: 'CSS',
  dart: 'Dart',
  diff: 'Diff',
  dockerfile: 'Dockerfile',
  docker: 'Dockerfile',
  elixir: 'Elixir',
  erlang: 'Erlang',
  go: 'Go',
  golang: 'Go',
  graphql: 'GraphQL',
  groovy: 'Groovy',
  haskell: 'Haskell',
  hs: 'Haskell',
  html: 'HTML',
  http: 'HTTP',
  ini: 'INI',
  java: 'Java',
  javascript: 'JavaScript',
  js: 'JavaScript',
  json: 'JSON',
  json5: 'JSON5',
  jsonc: 'JSON',
  jsx: 'JSX',
  kotlin: 'Kotlin',
  kt: 'Kotlin',
  latex: 'LaTeX',
  tex: 'LaTeX',
  less: 'Less',
  lua: 'Lua',
  makefile: 'Makefile',
  make: 'Makefile',
  markdown: 'Markdown',
  md: 'Markdown',
  mermaid: 'Mermaid',
  nginx: 'Nginx',
  objc: 'Objective-C',
  objectivec: 'Objective-C',
  'objective-c': 'Objective-C',
  ocaml: 'OCaml',
  perl: 'Perl',
  php: 'PHP',
  plaintext: 'Text',
  text: 'Text',
  txt: 'Text',
  powershell: 'PowerShell',
  ps1: 'PowerShell',
  pwsh: 'PowerShell',
  proto: 'Protobuf',
  protobuf: 'Protobuf',
  py: 'Python',
  python: 'Python',
  r: 'R',
  rb: 'Ruby',
  ruby: 'Ruby',
  rs: 'Rust',
  rust: 'Rust',
  scala: 'Scala',
  scss: 'SCSS',
  sass: 'Sass',
  sh: 'Shell',
  shell: 'Shell',
  zsh: 'Zsh',
  fish: 'Fish',
  console: 'Console',
  'shell-session': 'Console',
  sql: 'SQL',
  postgres: 'PostgreSQL',
  postgresql: 'PostgreSQL',
  mysql: 'MySQL',
  sqlite: 'SQLite',
  svelte: 'Svelte',
  swift: 'Swift',
  toml: 'TOML',
  ts: 'TypeScript',
  typescript: 'TypeScript',
  tsx: 'TSX',
  vue: 'Vue',
  wasm: 'WebAssembly',
  xml: 'XML',
  yaml: 'YAML',
  yml: 'YAML',
  zig: 'Zig'
}

export function languageName(id: string): string {
  const key = id.trim().toLowerCase()
  const known = NAMES[key]
  if (known) return known
  if (key === '') return ''
  return key.charAt(0).toUpperCase() + key.slice(1)
}
